### ISSUE TITLE
求详细的接线图

### ISSUE THREAD

**Issue by kuailezhiyuan** [butterfly-communtiy/water-heater#1]
家中的壁挂太阳能相同 求代码和更详细的教程

**Comment by zhang-wenchao** [comment]
固件是使用的 esphome，代码已经发出来了。

**Comment by zhang-wenchao** [comment]
感兴趣的话可以买个板子，然后 docker 起一个 esphome，把固件写进去。

**Comment by kuailezhiyuan** [comment]
我有esp32的板子的 但是想要知道怎么接线 博客里的草图没太看明白

**Comment by zhang-wenchao** [comment]
ESP32-C3-DevKitM-1 开发板接线：

GPIO2  SPI CLK    屏幕
GPIO3                                 温度传感器
GPIO4                                 加热继电器
GPIO5  SPI MOSI   屏幕
GPIO6  SPI DC       屏幕
GPIO7  SPI CS        屏幕
GPIO8  SPI RESET  屏幕
GPIO10                      加热提醒
GPIO18                      蓝色 LED
GPIO19                      红色 LED

**Comment by zhang-wenchao** [comment]
太阳能拆开前面板，排线没有花纹的那一侧朝向你。依次是：

1. NTC 热敏电阻
2. 未使用 （市电电流检测）
3. VCC 5V
4. 未使用 （市电电流检测）
5. GND
6. 未使用（继电器供电检测）
7. 加热继电器控制脚
8. 空引脚

**Comment by zhang-wenchao** [comment]
@kuailezhiyuan 看看还有没有其他问题。

**Comment by kuailezhiyuan** [comment]
我在第一步如何打开面板就遇到了困难，我拆不下来触摸按钮的那块塑料板，是需要大力出奇迹吗？

**Comment by zhang-wenchao** [comment]
是，底下有两个螺丝。用力撬开面板，从两边开始。最顶上有 1 个卡扣，最底下是分体的。

**Comment by kuailezhiyuan** [comment]
我拧开那两个螺丝了，最下面的分体的没太敢使劲撬。今晚找个翘板大力出奇迹试试

**Comment by kuailezhiyuan** [comment]
100K 欧姆分压电阻 应该怎么接呢？我理解的是排线的1号线（NTC 热敏电阻）并联100k电阻的一头，并联GPIO3。100k电阻的另一头接地

**Comment by zhang-wenchao** [comment]
原理图已经更新，参考原理图吧。

**Comment by kuailezhiyuan** [comment]
我按照原理图接线后，温度显示是-34度（实际51），不知道哪里出了问题。也可能是我错误接线了,没学过硬件相关的东西。看原理图是一知半解....
万用表测量了ntc的阻值4.031k
日志输出了这些
00:38:37 | [D] | [resistance:039] | 'resistance_sensor' - Resistance 169808.7Ω
00:38:37 | [D] | [sensor:094] | 'resistance_sensor': Sending state 169808.71875 Ω with 1 decimals of accuracy
00:38:37 | [D] | [ntc:026] | 'Current Temperature' - Temperature: -33.8°C
00:38:37 | [D] | [sensor:094] | 'Current Temperature': Sending state -33.82944 °C with 1 decimals of accuracy

**Comment by zhang-wenchao** [comment]
你拍个照？我看看你怎么接线的，另外日志多给一点。

**Comment by zhang-wenchao** [comment]
估计是超电压了，esp32c3 的话 adc 最高电压是 2.7v。你现在电阻换成 1k 欧姆的，然后代码  resistor: 1kOhm，configuration: DOWNSTREAM 试一下，应该没问题了。

**Comment by zhang-wenchao** [comment]
没有 1k 欧姆电阻的话，找几个电阻串联并联一下凑 1k 欧姆先试试。

**Comment by zhang-wenchao** [comment]
你在济南？

**Comment by kuailezhiyuan** [comment]
是的，在济南的。然后1k欧姆的电阻我好像没有，只有刚买的100k的，我可能要重新从淘宝买一些。然后我用的是esp32 就是最早的那个版本，不是c3

**Comment by kuailezhiyuan** [comment]
我可能找到了原因，我的热水器控制板和你的还是有一些不同的。
比如说 继电器是两个 需要7 8 都同时高电平输出才会启动加热。
我昨天测量，主板上ntc的母座一个端是直接与vcc导通的，另一头和排线1导通。（用的万用表）
这样的话热敏电阻应该是UPSTREAM。因为热敏电阻（可变电阻）更接近vcc。
我现在是配置的DOWNSTREAM，我怀疑esp32计算的是100kO电阻的电压，而不是热敏电阻的电压。
等我晚上回去试一试。

**Comment by zhang-wenchao** [comment]
可以加我微信：emhhbmd3ZW5jaGFvT0s=

**Comment by zhang-wenchao** [comment]
我的只需要 7 拉高就可以了，虽然有两个脚 6 和 7，但是 6 接到了 12V 上。

**Comment by zhang-wenchao** [comment]
看来每个子系列会有一点点区别

**Comment by zhang-wenchao** [comment]
最好是抛弃掉这个电源板，工频变压器发热也很大，琢磨线序也很烦人。

**Comment by zhang-wenchao** [comment]
但是我初衷是想看看最低多少成本能搞定这个事情，就保留了。

**Comment by kuailezhiyuan** [comment]
![QQ截图20240614205147](https://github.com/butterfly-communtiy/water-heater/assets/11912193/44947f6a-c538-4542-8c01-177125015e1e)
接入成功！感谢大佬的开源和指导！
